spring:
  datasource:
#    url: jdbc:mysql:db.sqlite
    url: jdbc:mysql://127.0.0.1:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: sa
#    password: password
    username: hoon
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect